import { useEffect, useState } from "react";
import { Image, Platform, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { HapticPressable } from "@/components/haptic-pressable";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { startOAuthCreateAccount, startOAuthLogin } from "@/constants/oauth";

export default function OnboardingScreen() {
  const router = useRouter();
  const { isAuthenticated, loading } = useAuth();
  const [authError, setAuthError] = useState<string | null>(null);
  useEffect(() => { if (!loading && isAuthenticated) router.replace("/(tabs)"); }, [isAuthenticated, loading, router]);
  async function openAuth(start: () => Promise<void>) { try { setAuthError(null); await start(); } catch (error) { setAuthError(error instanceof Error ? error.message : "TokFuel could not open secure sign-in. Please try again."); } }
  async function continueAsGuest() { if (isAuthenticated) router.replace("/(tabs)"); else await openAuth(startOAuthLogin); }
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.screen}><View style={styles.top}><Image source={require("@/assets/images/tokfuel-logo.png")} style={styles.logo} resizeMode="contain" /><Text style={styles.brand}>tokfuel</Text></View><View style={styles.hero}><View style={styles.glow} /><Text style={styles.eyebrow}>SEND A LITTLE MORE LOVE</Text><Text style={styles.title}>Fuel their next{`\n`}big moment.</Text><Text style={styles.body}>TokFuel makes it simple to send creator gifts for the TikTok accounts and moments that matter to you.</Text><View style={styles.points}><View style={styles.point}><Text style={styles.pointMark}>01</Text><Text style={styles.pointText}>Pick a gift category</Text></View><View style={styles.point}><Text style={styles.pointMark}>02</Text><Text style={styles.pointText}>Pay securely in naira</Text></View><View style={styles.point}><Text style={styles.pointMark}>03</Text><Text style={styles.pointText}>Track the delivery</Text></View></View></View>{authError && <Text style={styles.error}>{authError}</Text>}<View style={styles.actions}><HapticPressable style={styles.primary} onPress={continueAsGuest}><Text style={styles.primaryText}>{isAuthenticated ? "Continue to TokFuel" : "Get started"}</Text></HapticPressable>{!isAuthenticated && <><HapticPressable style={styles.secondary} onPress={() => openAuth(startOAuthCreateAccount)}><Text style={styles.secondaryText}>Create account</Text></HapticPressable><HapticPressable style={styles.login} onPress={() => openAuth(startOAuthLogin)}><Text style={styles.loginText}>Log in</Text></HapticPressable></>}</View><Text style={styles.legal}>Secure sessions · No TikTok password required</Text></View></ScreenContainer>;
}
const styles=StyleSheet.create({screen:{flex:1,paddingHorizontal:24,paddingTop:12,paddingBottom:10,justifyContent:"space-between"},top:{flexDirection:"row",alignItems:"center",gap:9},logo:{width:40,height:40,borderRadius:12},brand:{color:"#F8FAFC",fontSize:24,fontWeight:"900",letterSpacing:-1},hero:{paddingVertical:20},glow:{position:"absolute",width:250,height:250,borderRadius:125,backgroundColor:"#25F4EE",opacity:.07,right:-90,top:-30},eyebrow:{color:"#25F4EE",fontSize:10,fontWeight:"900",letterSpacing:1.4},title:{color:"#F8FAFC",fontSize:44,lineHeight:46,fontWeight:"900",letterSpacing:-1.8,marginTop:15},body:{color:"#A3A3B2",fontSize:15,lineHeight:23,marginTop:16,maxWidth:340},points:{marginTop:28,gap:15},point:{flexDirection:"row",alignItems:"center",gap:12},pointMark:{color:"#FE2C55",fontSize:11,fontWeight:"900",width:24},pointText:{color:"#D7D7E0",fontSize:14,fontWeight:"700"},error:{color:"#FFB6C5",fontSize:12,lineHeight:17,backgroundColor:"#2A1720",padding:12,borderRadius:10},actions:{gap:10},primary:{backgroundColor:"#25F4EE",borderRadius:14,paddingVertical:16,alignItems:"center"},primaryText:{color:"#0B0B0F",fontWeight:"900",fontSize:14},secondary:{backgroundColor:"#FE2C55",borderRadius:14,paddingVertical:16,alignItems:"center"},secondaryText:{color:"#FFFFFF",fontWeight:"900",fontSize:14},login:{paddingVertical:11,alignItems:"center"},loginText:{color:"#25F4EE",fontWeight:"800",fontSize:13},legal:{color:"#6F707D",fontSize:10,textAlign:"center",marginTop:12}});
