import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function GiftCheckoutScreen() {
  const router = useRouter();
  const { giftId } = useLocalSearchParams<{ giftId?: string }>();
  const [link, setLink] = useState("");
  const [quantity, setQuantity] = useState("");
  const giftsQuery = trpc.smm.getServices.useQuery();
  const gift = giftsQuery.data?.find((item) => item.giftId === String(giftId));
  const quantityNumber = Number(quantity);
  const costQuery = trpc.smm.calculateCost.useQuery({ giftId: giftId ?? "", quantity: quantityNumber }, { enabled: Boolean(giftId && gift && quantityNumber >= 500 && quantityNumber % 500 === 0), retry: false });

  if (!giftId || (!giftsQuery.isLoading && !gift)) return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.empty}><Ionicons name="gift-outline" size={34} color="#25F4EE" /><Text style={styles.emptyTitle}>Choose a gift first</Text><Text style={styles.emptyText}>Select a gift from the live TokFuel gift grid.</Text><Pressable style={styles.button} onPress={() => router.push("/(tabs)/services")}><Text style={styles.buttonText}>View gifts</Text></Pressable></View></ScreenContainer>;

  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>TOKFUEL GIFT</Text><Text style={styles.title}>{gift?.title}</Text><Text style={styles.subtitle}>Choose a quantity and send this gift to a TikTok account or video.</Text><View style={styles.serviceCard}><Ionicons name="gift-outline" size={22} color="#25F4EE" /><View style={{ flex: 1, marginLeft: 11 }}><Text style={styles.serviceCategory}>{gift?.category}</Text><Text style={styles.serviceName}>{gift?.description}</Text></View></View><View style={styles.card}><Text style={styles.label}>TikTok account or video link</Text><View style={styles.input}><Ionicons name="logo-tiktok" size={18} color="#25F4EE" /><TextInput value={link} onChangeText={setLink} placeholder="https://tiktok.com/@creator" placeholderTextColor="#6B7280" style={styles.inputText} autoCapitalize="none" /></View><Text style={styles.label}>Gift quantity</Text><View style={styles.input}><Ionicons name="add-circle-outline" size={18} color="#6B7280" /><TextInput value={quantity} onChangeText={setQuantity} placeholder={`From ${gift?.minQuantity.toLocaleString()} · add 500`} placeholderTextColor="#6B7280" keyboardType="number-pad" style={styles.inputText} /></View><Text style={styles.range}>Available from {gift?.minQuantity.toLocaleString()} to {gift?.maxQuantity.toLocaleString()} · 500-unit steps</Text></View>{costQuery.data && <View style={styles.summary}><Text style={styles.summaryLabel}>Your gift total</Text><Text style={styles.total}>₦{costQuery.data.customerTotal.toLocaleString("en-NG", { minimumFractionDigits: 2 })}</Text><Text style={styles.summaryNote}>{quantityNumber.toLocaleString()} units · Final customer price</Text></View>}{costQuery.isError && <Text style={styles.error}>That quantity is not available for this gift. Please check the live limits.</Text>}<Pressable style={[styles.button, (!link || !quantity || !costQuery.data) && styles.buttonDisabled]} disabled={!link || !quantity || !costQuery.data} onPress={() => router.push("/(tabs)/orders")}><Text style={styles.buttonText}>Continue to payment</Text><Ionicons name="arrow-forward" size={18} color="#0B0B0F" /></Pressable><View style={styles.safe}><Ionicons name="lock-closed-outline" size={14} color="#31D158" /><Text style={styles.safeText}>Secure checkout · No TikTok password required</Text></View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 20, paddingBottom: 40 }, kicker: { color: "#25F4EE", fontWeight: "800", fontSize: 10, letterSpacing: 1.2 }, title: { color: "#F8FAFC", fontWeight: "800", fontSize: 32, marginTop: 10 }, subtitle: { color: "#9CA3AF", fontSize: 14, lineHeight: 21, marginTop: 8, marginBottom: 18 }, serviceCard: { flexDirection: "row", alignItems: "center", backgroundColor: "#132326", borderRadius: 16, padding: 14, marginBottom: 14, borderWidth: 1, borderColor: "#2A4C50" }, serviceCategory: { color: "#25F4EE", fontWeight: "800", fontSize: 11 }, serviceName: { color: "#B7E9E7", fontSize: 10, lineHeight: 15, marginTop: 4 }, card: { backgroundColor: "#15151C", borderRadius: 18, borderWidth: 1, borderColor: "#292935", padding: 17 }, label: { color: "#F8FAFC", fontSize: 12, fontWeight: "800", marginTop: 8, marginBottom: 9 }, input: { height: 47, flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: "#0D0D13", borderColor: "#2A2A35", borderWidth: 1, borderRadius: 12, paddingHorizontal: 12 }, inputText: { flex: 1, color: "#F8FAFC", fontSize: 13 }, range: { color: "#6F707D", fontSize: 10, marginTop: 10 }, summary: { marginTop: 17, padding: 17, borderRadius: 16, backgroundColor: "#171722", borderWidth: 1, borderColor: "#2A2A35" }, summaryLabel: { color: "#9CA3AF", fontSize: 12 }, total: { color: "#25F4EE", fontSize: 27, fontWeight: "800", marginTop: 6 }, summaryNote: { color: "#6F707D", fontSize: 11, marginTop: 5 }, error: { color: "#FFB6C5", fontSize: 12, marginTop: 12 }, button: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 9, backgroundColor: "#25F4EE", borderRadius: 13, paddingVertical: 14, marginTop: 17 }, buttonDisabled: { opacity: 0.35 }, buttonText: { color: "#0B0B0F", fontWeight: "800", fontSize: 13 }, safe: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 6, marginTop: 16 }, safeText: { color: "#6B7280", fontSize: 10 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", gap: 11 }, emptyTitle: { color: "#F8FAFC", fontWeight: "800", fontSize: 19 }, emptyText: { color: "#9CA3AF", textAlign: "center", fontSize: 12 },
});
