import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";

export default function GiftCheckoutScreen() {
  const router = useRouter(); const [link, setLink] = useState(""); const [amount, setAmount] = useState("1000");
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>GIFT CARD CHECKOUT</Text><Text style={styles.title}>Send a creator gift</Text><Text style={styles.subtitle}>Your gift is applied to the TikTok account you choose. No passwords required.</Text><View style={styles.card}><Text style={styles.label}>TikTok account or video link</Text><View style={styles.input}><Ionicons name="logo-tiktok" size={18} color="#25F4EE" /><TextInput value={link} onChangeText={setLink} placeholder="https://tiktok.com/@creator" placeholderTextColor="#6B7280" style={styles.inputText} autoCapitalize="none" /></View><Text style={styles.label}>Gift amount</Text><View style={styles.amountRow}>{["500", "1000", "2500", "5000"].map((value) => <Pressable key={value} onPress={() => setAmount(value)} style={[styles.amountChip, amount === value && styles.amountActive]}><Text style={[styles.amountChipText, amount === value && styles.amountActiveText]}>₦{value}</Text></Pressable>)}</View><Text style={styles.label}>Add a note (optional)</Text><View style={styles.input}><Ionicons name="chatbubble-ellipses-outline" size={18} color="#6B7280" /><TextInput placeholder="Keep creating, we see you!" placeholderTextColor="#6B7280" style={styles.inputText} /></View></View><View style={styles.summary}><Text style={styles.summaryLabel}>Gift total</Text><Text style={styles.total}>₦{Number(amount).toLocaleString()}</Text><Text style={styles.summaryNote}>TokFuel gift card credit · Instant delivery</Text></View><Pressable style={styles.button} onPress={() => router.push("/(tabs)/orders")}><Text style={styles.buttonText}>Continue to secure payment</Text><Ionicons name="arrow-forward" size={18} color="#0B0B0F" /></Pressable><View style={styles.safe}><Ionicons name="lock-closed-outline" size={14} color="#31D158" /><Text style={styles.safeText}>Secure payment powered for Nigeria</Text></View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 20, paddingBottom: 40 }, kicker: { color: "#25F4EE", fontWeight: "800", fontSize: 10, letterSpacing: 1.2 }, title: { color: "#F8FAFC", fontWeight: "800", fontSize: 32, marginTop: 10 }, subtitle: { color: "#9CA3AF", fontSize: 14, lineHeight: 21, marginTop: 8, marginBottom: 25 }, card: { backgroundColor: "#15151C", borderRadius: 18, borderWidth: 1, borderColor: "#292935", padding: 17 }, label: { color: "#F8FAFC", fontSize: 12, fontWeight: "800", marginTop: 8, marginBottom: 9 }, input: { height: 47, flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: "#0D0D13", borderColor: "#2A2A35", borderWidth: 1, borderRadius: 12, paddingHorizontal: 12 }, inputText: { flex: 1, color: "#F8FAFC", fontSize: 13 }, amountRow: { flexDirection: "row", gap: 7, marginBottom: 8 }, amountChip: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, backgroundColor: "#20202A" }, amountActive: { backgroundColor: "#25F4EE" }, amountChipText: { color: "#A3A3B2", fontWeight: "700", fontSize: 12 }, amountActiveText: { color: "#0B0B0F" }, summary: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", marginTop: 25, padding: 18, borderRadius: 16, backgroundColor: "#171722" }, summaryLabel: { color: "#9CA3AF", fontSize: 13, flex: 1 }, total: { color: "#25F4EE", fontSize: 23, fontWeight: "800" }, summaryNote: { width: "100%", color: "#6B7280", fontSize: 11, marginTop: 8 }, button: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 9, backgroundColor: "#25F4EE", borderRadius: 13, paddingVertical: 14, marginTop: 17 }, buttonText: { color: "#0B0B0F", fontWeight: "800", fontSize: 13 }, safe: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 6, marginTop: 16 }, safeText: { color: "#6B7280", fontSize: 10 },
});
