import { useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { HapticPressable } from "@/components/haptic-pressable";
import { trpc } from "@/lib/trpc";

export default function OrdersScreen() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const walletQuery = trpc.payments.wallet.useQuery({ email }, { enabled: /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email) });
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>YOUR TOKFUEL WALLET</Text><View style={styles.wallet}><View style={styles.walletCopy}><Text style={styles.walletLabel}>Refund balance</Text><Text style={styles.balance}>{walletQuery.data ? `₦${walletQuery.data.balance.toLocaleString("en-NG", { minimumFractionDigits: 2 })}` : "—"}</Text><Text style={styles.walletNote}>Only failed or unsuccessful purchases are credited here.</Text></View><Ionicons name="wallet-outline" color="#25F4EE" size={29} /></View><View style={styles.emailCard}><Text style={styles.emailLabel}>Check your refund balance</Text><Text style={styles.emailHelp}>Use the same email used for your TokFuel payment.</Text><View style={styles.input}><Ionicons name="mail-outline" size={18} color="#25F4EE" /><TextInput value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor="#6B7280" style={styles.inputText} autoCapitalize="none" keyboardType="email-address" /></View></View><View style={styles.header}><Text style={styles.title}>Gift history</Text><HapticPressable onPress={() => router.push("/(tabs)/services")}><Text style={styles.action}>Send a gift</Text></HapticPressable></View><View style={styles.empty}><Ionicons name="receipt-outline" size={30} color="#25F4EE" /><Text style={styles.emptyTitle}>Your orders appear here</Text><Text style={styles.emptyText}>After payment, this area will show gift status and any refund balance created by an unsuccessful order.</Text><HapticPressable style={styles.button} onPress={() => router.push("/(tabs)/services")}><Text style={styles.buttonText}>Browse gifts</Text></HapticPressable></View><View style={styles.help}><Ionicons name="shield-checkmark-outline" color="#A98CFF" size={21}/><View style={{flex:1}}><Text style={styles.helpTitle}>Refund balance only</Text><Text style={styles.helpText}>There is no add-money or deposit feature. Successful gifts are not automatically refunded.</Text></View></View></ScrollView></ScreenContainer>;
}
const styles=StyleSheet.create({content:{paddingTop:20,paddingBottom:40},kicker:{color:"#25F4EE",fontSize:10,fontWeight:"800",letterSpacing:1.2},wallet:{marginTop:15,padding:20,borderRadius:19,backgroundColor:"#171722",borderWidth:1,borderColor:"#2A2A35",flexDirection:"row",justifyContent:"space-between"},walletCopy:{flex:1},walletLabel:{color:"#9CA3AF",fontSize:12},balance:{color:"#F8FAFC",fontSize:28,fontWeight:"800",marginTop:7},walletNote:{color:"#31D158",fontSize:11,lineHeight:17,marginTop:6},emailCard:{marginTop:13,padding:15,borderRadius:16,backgroundColor:"#15151C",borderWidth:1,borderColor:"#292935"},emailLabel:{color:"#F8FAFC",fontSize:13,fontWeight:"800"},emailHelp:{color:"#858594",fontSize:11,marginTop:4,marginBottom:11},input:{height:45,flexDirection:"row",alignItems:"center",gap:9,backgroundColor:"#0D0D13",borderColor:"#2A2A35",borderWidth:1,borderRadius:12,paddingHorizontal:12},inputText:{flex:1,color:"#F8FAFC",fontSize:13},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:30,marginBottom:13},title:{color:"#F8FAFC",fontWeight:"800",fontSize:21},action:{color:"#25F4EE",fontSize:12,fontWeight:"800",paddingVertical:5},empty:{alignItems:"center",padding:28,borderRadius:17,backgroundColor:"#15151C",borderWidth:1,borderColor:"#292935"},emptyTitle:{color:"#F8FAFC",fontWeight:"800",fontSize:16,marginTop:12},emptyText:{color:"#858594",fontSize:11,lineHeight:17,textAlign:"center",marginTop:6},button:{backgroundColor:"#25F4EE",paddingHorizontal:16,paddingVertical:11,borderRadius:11,marginTop:17},buttonText:{color:"#0B0B0F",fontSize:12,fontWeight:"800"},help:{flexDirection:"row",gap:10,alignItems:"center",padding:15,borderRadius:16,borderWidth:1,borderColor:"#40375A",marginTop:16},helpTitle:{color:"#F8FAFC",fontWeight:"800",fontSize:13},helpText:{color:"#858594",fontSize:11,lineHeight:17,marginTop:4}});
