import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";

export default function OrdersScreen() {
  const router = useRouter();
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>YOUR TOKFUEL WALLET</Text><View style={styles.wallet}><View><Text style={styles.walletLabel}>Gift wallet</Text><Text style={styles.balance}>Ready when you are</Text><Text style={styles.walletNote}>Payment options will appear at checkout</Text></View><Ionicons name="wallet-outline" color="#25F4EE" size={29} /></View><View style={styles.header}><Text style={styles.title}>Gift history</Text><Pressable onPress={() => router.push("/(tabs)/services")}><Text style={styles.action}>Send a gift</Text></Pressable></View><View style={styles.empty}><Ionicons name="receipt-outline" size={30} color="#25F4EE" /><Text style={styles.emptyTitle}>No gifts sent yet</Text><Text style={styles.emptyText}>Choose a gift, enter the TikTok link, and continue to secure payment.</Text><Pressable style={styles.button} onPress={() => router.push("/(tabs)/services")}><Text style={styles.buttonText}>Browse gifts</Text></Pressable></View><View style={styles.help}><Ionicons name="shield-checkmark-outline" color="#A98CFF" size={21}/><View style={{flex:1}}><Text style={styles.helpTitle}>Simple, private gifting</Text><Text style={styles.helpText}>Customers see TokFuel gifts and final prices—not provider details or wholesale information.</Text></View></View></ScrollView></ScreenContainer>;
}
const styles=StyleSheet.create({content:{paddingTop:20,paddingBottom:40},kicker:{color:"#25F4EE",fontSize:10,fontWeight:"800",letterSpacing:1.2},wallet:{marginTop:15,padding:20,borderRadius:19,backgroundColor:"#171722",borderWidth:1,borderColor:"#2A2A35",flexDirection:"row",justifyContent:"space-between"},walletLabel:{color:"#9CA3AF",fontSize:12},balance:{color:"#F8FAFC",fontSize:22,fontWeight:"800",marginTop:7},walletNote:{color:"#31D158",fontSize:11,marginTop:6},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:30,marginBottom:13},title:{color:"#F8FAFC",fontWeight:"800",fontSize:21},action:{color:"#25F4EE",fontSize:12,fontWeight:"800"},empty:{alignItems:"center",padding:28,borderRadius:17,backgroundColor:"#15151C",borderWidth:1,borderColor:"#292935"},emptyTitle:{color:"#F8FAFC",fontWeight:"800",fontSize:16,marginTop:12},emptyText:{color:"#858594",fontSize:11,lineHeight:17,textAlign:"center",marginTop:6},button:{backgroundColor:"#25F4EE",paddingHorizontal:16,paddingVertical:11,borderRadius:11,marginTop:17},buttonText:{color:"#0B0B0F",fontSize:12,fontWeight:"800"},help:{flexDirection:"row",gap:10,alignItems:"center",padding:15,borderRadius:16,borderWidth:1,borderColor:"#40375A",marginTop:16},helpTitle:{color:"#F8FAFC",fontWeight:"800",fontSize:13},helpText:{color:"#858594",fontSize:11,lineHeight:17,marginTop:4}});
